### ISSUE TITLE
EOF Exception in dgca-verifier-service

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-verifier-service#32]
Dear Devs, 

Please can you review the exception I'm finding in the Verifier Service Logs

```
java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1345) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1255) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:794) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:359) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2021-05-12 06:19:28.594 DEBUG 7 --- [nio-8080-exec-9] o.apache.coyote.http11.Http11Processor   : Error state [CLOSE_CONNECTION_NOW] reported while processing request

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1345) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1255) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:794) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:359) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.44.jar!/:9.0.44]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by slaurenz** [comment]
Dear @psavva,
thanks for your report. Unfortunately I don't have the error in my log, and I was not able to reproduce it.

Can you please provide some more Information about your setup and the entire log, so that we can have more insights when the exception occurs.

Thanks

**Comment by psavva** [comment]
Hi @slaurenz 

I have my log level set to DEBUG, 

I'm simply running the verifier service connected on the TEST DGCG.
Upon download, the errors appear in the log.

Attaching a full log:
[verifier.zip](https://github.com/eu-digital-green-certificates/dgca-verifier-service/files/6464803/verifier.zip)

**Comment by f11h** [comment]
What kind of device/http-client are you using when sending your request to the service.

For me it looks like your request is not correct.

**Comment by psavva** [comment]
Hi @f11h 

I'm only using the Template Applications as per this github repository.

The Android Verification App and the Android Wallet app are the only clients connecting to the Verifier-Service.

**Comment by f11h** [comment]
But there seems to be a reverse proxy between your android phone and verifier service?

**Comment by psavva** [comment]
Correct, This is going though Kubernetes via Nginx ingress

**Comment by psavva** [comment]
After much research, it seems this is not related to either the Reverse Proxy or the Verifier Service.
The problem seems to be related to the java language, and is concluded as "Correct Behavior".

If you set on DEBUG on Logging Level Root, do you not simulate the same?

In any case, seems like it's "normal behavior"
https://github.com/spring-cloud/spring-cloud-dataflow/issues/1306
